#!/bin/bash
# Script to retrieve VPC, subnets, and default security group for EKS cluster creation
# The VPC name below is the one generated by CloudFormation when creating the VPC

VPC_NAME="VPC-K8S"  # Name tag of the VPC created by CloudFormation

# Get VPC ID by the tag name
VPC_ID=$(aws ec2 describe-vpcs \
    --filters "Name=tag:Name,Values=$VPC_NAME" \
    --query "Vpcs[0].VpcId" \
    --output text)

# Public Subnets
PUBLIC_SUBNETS=($(aws ec2 describe-subnets \
    --filters "Name=vpc-id,Values=$VPC_ID" "Name=tag:Public,Values=true" \
    --query "Subnets[*].SubnetId" \
    --output text))

# Private Subnets
PRIVATE_SUBNETS=($(aws ec2 describe-subnets \
    --filters "Name=vpc-id,Values=$VPC_ID" "Name=tag:Private,Values=true" \
    --query "Subnets[*].SubnetId" \
    --output text))

# Join all subnets into a comma-separated list for EKS cluster creation
subnetIds=$(IFS=,; echo "${PUBLIC_SUBNETS[*]},${PRIVATE_SUBNETS[*]}")

# Get default security group ID for the VPC
SECURITY_GROUP=$(aws ec2 describe-security-groups \
    --filters Name=vpc-id,Values=$VPC_ID Name=group-name,Values=default \
    --query "SecurityGroups[0].GroupId" --output text)

# Create cluster 
# aws eks create-cluster --role-arn $ROLE_ARN --resources-vpc-config subnetIds=$subnetIds,securityGroupIds=$SECURITY_GROUP

